name: Daily Job Tracker

on:
  schedule:
    - cron: '0 8 * * *' # 
  workflow_dispatch: 

permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run ETL Pipeline
        env:
          RAPID_API_KEY: ${{ secrets.RAPID_API_KEY }}
        run: python main.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # הוספנו כאן את all_jobs.csv לרשימה כדי שיופיע בגיטהאב
          git add -f top_technologies.png jobs_data.sqlite3 all_jobs.csv
          git commit -m "Auto-update: New job data, visualization and CSV report" || exit 0
          git pull --rebase origin main
          git push
